services:
  - type: web
    name: record-finder-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DISCOGS_TOKEN
        sync: false
      - key: DISCOGS_CONSUMER_KEY
        sync: false
      - key: DISCOGS_CONSUMER_SECRET
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FLASK_ENV
        value: production
